### PR TITLE
Devops elk

### PR DESCRIPTION
**Pull request by Akshaykumar-Hingarajiya**

### CODE REVIEW

**Comment by jagdish-zymr** [comment]
@Akshaykumar-Hingarajiya 
docker.elastic.co/beats/filebeat:7.17.7. upload this image to zymr nexus and use this only.

**Comment by Akshaykumar-Hingarajiya** [comment]
Done.

**Comment by jagdish-zymr** [comment]
@Akshaykumar-Hingarajiya  why use static ip?

**Comment by Akshaykumar-Hingarajiya** [comment]
Done.

**Review by jagdish-zymr — APPROVED** [review]

**Review by chirag-zymr — APPROVED** [review]

**Pull request merged**
